Added tutorial for building a basic Rust CLI app
codecrafters-io/build-your-own-x pull request #748
Opened 2022-06-17 12:00 UTC by kkaosninja

Linking to the Rust CLI book => https://rust-cli.github.io/book/tutorial/index.html

2022-06-17 12:43 UTC, MuhammedZakir requested changes

2022-06-17 12:43 UTC, MuhammedZakir commented on README.md
> +* [**Rust**: _Rust 15-min CLI app tutorial](https://rust-cli.github.io/book/tutorial/index.html)
```suggestion
* [**Rust**: _Rust 15-min CLI app tutorial_](https://rust-cli.github.io/book/tutorial/index.html)
```

2022-09-03 17:34 UTC, imlakshay08 approved these changes

2022-09-13 02:22 UTC, Givs approved these changes

2023-07-04 13:04 UTC, closed without merging